name = "LeadLagAssistant"
uuid = "340f1b4a-b988-4648-82ed-1b76f38831ff"
authors = ["Kelvyn Baruc Sánchez Sánchez <kelvyn.baruc@gmail.com>"]
version = "0.1.0"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
